-- Enable PostGIS extension
create extension if not exists postgis;

-- Enums
create type role_enum as enum ('user', 'admin');
create type location_category_enum as enum ('sungai', 'pinggir_jalan', 'area_publik', 'tanah_kosong', 'lainnya');
create type waste_type_enum as enum ('organik', 'anorganik', 'campuran');
create type waste_volume_enum as enum ('1_pickup', '1_truk_kecil', '1_truk_besar', 'lebih_dari_1_truk_besar', 'kurang_dari_30kg', '30_50kg', '50_100kg', 'lebih_dari_100kg'); -- added older volumes just in case
create type hazard_risk_enum as enum ('tidak_ada', 'rendah', 'menengah', 'tinggi');
create type campaign_status_enum as enum ('upcoming', 'ongoing', 'finished', 'cancelled');
create type notification_type_enum as enum ('report_status', 'campaign_reminder', 'campaign_update', 'system');
create type campaign_organizer_type_enum as enum ('personal', 'organization');
create type report_status_enum as enum ('pending', 'approved', 'rejected', 'hazardous', 'finished');

-- Profiles Table
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  exp integer default 0 not null,
  role role_enum default 'user'::role_enum not null
);

-- Reports Table
create table public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  image_urls text[] not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  waste_type waste_type_enum not null,
  waste_volume text not null, -- using text since there was a mix of enums in types, but constraint can be added
  location_category text not null,
  hazard_risk hazard_risk_enum default 'tidak_ada'::hazard_risk_enum not null,
  notes text,
  location geography(point, 4326) not null,
  status report_status_enum default 'pending'::report_status_enum not null,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamp with time zone,
  admin_notes text
);

-- Campaigns Table
create table public.campaigns (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  max_participants integer default 50 not null,
  min_participants integer default 5 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  status campaign_status_enum default 'upcoming'::campaign_status_enum not null,
  report_id bigint references public.reports(id) on delete cascade not null,
  organizer_name text not null,
  organizer_type campaign_organizer_type_enum not null
);

-- Campaign Participants Table
create table public.campaign_participants (
  campaign_id bigint references public.campaigns(id) on delete cascade not null,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_attended boolean,
  primary key (campaign_id, profile_id)
);

-- Notifications Table
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  message text not null,
  type notification_type_enum not null,
  related_id bigint,
  is_read boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Basic RPC (Mocked for Demo purposes)
create or replace function get_reports_with_coordinates()
returns table (
  id bigint,
  user_id uuid,
  image_urls text[],
  created_at timestamp with time zone,
  waste_type waste_type_enum,
  waste_volume text,
  location_category text,
  hazard_risk hazard_risk_enum,
  notes text,
  status report_status_enum,
  latitude float,
  longitude float
) as $$
begin
  return query
  select 
    r.id, r.user_id, r.image_urls, r.created_at, r.waste_type, r.waste_volume, 
    r.location_category, r.hazard_risk, r.notes, r.status,
    st_y(r.location::geometry) as latitude,
    st_x(r.location::geometry) as longitude
  from public.reports r
  where r.status = 'approved' or r.status = 'hazardous';
end;
$$ language plpgsql;

create or replace function get_user_reports_with_coordinates(p_user_id uuid)
returns table (
  id bigint,
  user_id uuid,
  image_urls text[],
  created_at timestamp with time zone,
  waste_type waste_type_enum,
  waste_volume text,
  location_category text,
  hazard_risk hazard_risk_enum,
  notes text,
  status report_status_enum,
  admin_notes text,
  latitude float,
  longitude float
) as $$
begin
  return query
  select 
    r.id, r.user_id, r.image_urls, r.created_at, r.waste_type, r.waste_volume, 
    r.location_category, r.hazard_risk, r.notes, r.status, r.admin_notes,
    st_y(r.location::geometry) as latitude,
    st_x(r.location::geometry) as longitude
  from public.reports r
  where r.user_id = p_user_id;
end;
$$ language plpgsql;

create or replace function get_pending_reports()
returns table (
  id bigint,
  user_id uuid,
  image_urls text[],
  created_at timestamp with time zone,
  waste_type waste_type_enum,
  waste_volume text,
  location_category text,
  hazard_risk hazard_risk_enum,
  notes text,
  status report_status_enum,
  latitude float,
  longitude float
) as $$
begin
  return query
  select 
    r.id, r.user_id, r.image_urls, r.created_at, r.waste_type, r.waste_volume, 
    r.location_category, r.hazard_risk, r.notes, r.status,
    st_y(r.location::geometry) as latitude,
    st_x(r.location::geometry) as longitude
  from public.reports r
  where r.status = 'pending';
end;
$$ language plpgsql;

-- Storage Buckets (Run this, but might need manual creation in dashboard if fails)
insert into storage.buckets (id, name, public) values ('reports', 'reports', true);

-- Disable RLS for emergency demo (NOT FOR PRODUCTION)
alter table public.profiles disable row level security;
alter table public.reports disable row level security;
alter table public.campaigns disable row level security;
alter table public.campaign_participants disable row level security;
alter table public.notifications disable row level security;

-- Trigger to create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, role)
  values (new.id, 'user');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
